# Copyright 2021 ConsenSys AG.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
# an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

# Project information
site_name: Quorum Key Manager
site_url: https://docs.quorum-key-manager.consensys.net/
site_description: Quorum Key Manager documentation.
site_author: Quorum Key Manager community
copyright: Quorum Key Manager and its documentation are licensed under Apache 2.0 license

#extra project info and template customisation
extra:
  logo_is_text: true
  latest_version_warning:
    url_contains: /latest/
    text: 'You are reading Quorum Key Manager development version documentation and
    some displayed features may not be available in the stable release.
    You can switch to stable version using the version box at screen bottom.'
  support:
    tool: Discord
    channel: https://discord.gg/5U9Jwp7
    email: quorum@consensys.net
    website: https://consensys.net/quorum/developers
    company: Consensys
    issues: https://github.com/Consensys/quorum-key-manager/issues
  google:
    site_verification: 'za1cLzyS6LXDGO-pMzvfQdYTZ0Zc67uZtY0asA4YXZ0'
    tag_manager: 'GTM-5FCWH9Q'


# Software Repository
repo_name: Consensys/quorum-key-manager
repo_url: https://github.com/Consensys/quorum-key-manager

theme:
  name: material
  custom_dir: common/custom_theme
  palette:
    primary: deep-orange
    accent: teal
  logo: 'Images/logo.svg'
  favicon: 'Images/favicon.svg'
nav:
    - How to:
        - Get started with Quorum Key Manager:
            - Install binary distribution: HowTo/Get-Started/Install-Binaries.md
            - Run Quorum Key Manager from Docker image: HowTo/Get-Started/Use-Docker.md
            - Build from source: HowTo/Get-Started/Build-From-Source.md
            - Start Quorum Key Manager: HowTo/Get-Started/Start.md
    - Concepts:
        - Architecture: Concepts/ArchitectureOverview.md
    - Tutorials:
        - Overview: Tutorials/Overview.md
    - Reference:
        - Command Line Options: Reference/CLI-Syntax.md
        - REST API methods: Reference/Rest.md

markdown_extensions:
  - toc:
      permalink: 
      toc_depth: 4
  - codehilite
  - pymdownx.tabbed
  - pymdownx.superfences
  - markdown_include.include:
      base_path: docs
  - admonition
  - footnotes
  - def_list
  - abbr
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - meta
  - smarty

plugins:
  - search:
      lang: 'en'
      separator: '[\s]+'
  - markdownextradata
  - redirects:
      redirect_maps:
        # Configure redirects using key:value pairs:
        # old_path.md: new_path.md
        # you can't use an already redirected path as an old_path.
        # new_path can be a file inside the docs/ folder or any URL (http://...)
        # Reference/EthSigner-CLI.md: Reference/CLI/CLI-Syntax.md
